#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: 
      - source

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Sync New Code
        run: |
          git init
          git remote add openwrt https://github.com/coolsnowwolf/lede.git
          git pull openwrt master
          git remote -v
